-- Student IDs generated by the application use the form "std-" + UUID
-- (40 characters). The original enrollment reference columns were limited
-- to 36 characters, preventing newly created students from being enrolled.
DO $$
BEGIN
    IF to_regclass('public.enrollments') IS NOT NULL THEN
        ALTER TABLE enrollments
            ALTER COLUMN student_id TYPE varchar(64),
            ALTER COLUMN course_id TYPE varchar(64);
    END IF;
END $$;
